services:
  - type: web
    name: the-ancestor
    env: python
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python ancestor.py
    disk:
      name: ancestor-disk
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: ANCESTOR_ACTIVE
        value: "true"
      - key: PORT
        value: "10000"
