services:
  - type: web
    name: the-ancestor
    env: python
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ancestor:app --bind 0.0.0.0:$PORT --timeout 120 --worker-class gevent --workers 1
    disk:
      name: ancestor-disk
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: ANCESTOR_ACTIVE
        value: "true"
